/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class Delta {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Delta(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Delta obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_Delta(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Delta() {
    this(bcJNI.new_Delta(), true);
  }

  public String toJson() {
    return bcJNI.Delta_toJson(swigCPtr, this);
  }

}
