/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public enum Direction {
  North(0),
  Northeast(1),
  East(2),
  Southeast(3),
  South(4),
  Southwest(5),
  West(6),
  Northwest(7),
  Center(8);

  public final int swigValue() {
    return swigValue;
  }

  public static Direction swigToEnum(int swigValue) {
    Direction[] swigValues = Direction.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Direction swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Direction.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Direction() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Direction(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Direction(Direction swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

