/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class InitialTurnApplication {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected InitialTurnApplication(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(InitialTurnApplication obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_InitialTurnApplication(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InitialTurnApplication() {
    this(bcJNI.new_InitialTurnApplication(), true);
  }

  public void setStart_turn(StartTurnMessage value) {
    bcJNI.InitialTurnApplication_start_turn_set(swigCPtr, this, StartTurnMessage.getCPtr(value), value);
  }

  public StartTurnMessage getStart_turn() {
    long cPtr = bcJNI.InitialTurnApplication_start_turn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StartTurnMessage(cPtr, false);
  }

  public void setViewer(ViewerKeyframe value) {
    bcJNI.InitialTurnApplication_viewer_set(swigCPtr, this, ViewerKeyframe.getCPtr(value), value);
  }

  public ViewerKeyframe getViewer() {
    long cPtr = bcJNI.InitialTurnApplication_viewer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ViewerKeyframe(cPtr, false);
  }

}
