/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class Location {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Location(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Location obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_Location(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Location() {
    this(bcJNI.new_Location(), true);
  }

  public boolean isOnMap() {
    return bcJNI.Location_isOnMap(swigCPtr, this);
  }

  public boolean isOnPlanet(Planet planet) {
    return bcJNI.Location_isOnPlanet(swigCPtr, this, planet.swigValue());
  }

  public MapLocation mapLocation() {
    long cPtr = bcJNI.Location_mapLocation(swigCPtr, this);
    return (cPtr == 0) ? null : new MapLocation(cPtr, true);
  }

  public boolean isInGarrison() {
    return bcJNI.Location_isInGarrison(swigCPtr, this);
  }

  public int structure() {
    return bcJNI.Location_structure(swigCPtr, this);
  }

  public boolean isInSpace() {
    return bcJNI.Location_isInSpace(swigCPtr, this);
  }

  public boolean isAdjacentTo(Location o) {
    return bcJNI.Location_isAdjacentTo(swigCPtr, this, Location.getCPtr(o), o);
  }

  public boolean isWithinRange(long range, Location o) {
    return bcJNI.Location_isWithinRange(swigCPtr, this, range, Location.getCPtr(o), o);
  }

  public String toString() {
    return bcJNI.Location_toString(swigCPtr, this);
  }

  public Location clone() {
    long cPtr = bcJNI.Location_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Location(cPtr, true);
  }

  public boolean equals(Location other) {
    return bcJNI.Location_equals(swigCPtr, this, Location.getCPtr(other), other);
  }

  public String toJson() {
    return bcJNI.Location_toJson(swigCPtr, this);
  }

}
