/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class OrbitPattern {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OrbitPattern(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OrbitPattern obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_OrbitPattern(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OrbitPattern(long amplitude, long period, long center) {
    this(bcJNI.new_OrbitPattern(amplitude, period, center), true);
  }

  public boolean validate() {
    return bcJNI.OrbitPattern_validate(swigCPtr, this);
  }

  public long duration(long round) {
    return bcJNI.OrbitPattern_duration(swigCPtr, this, round);
  }

  public String toJson() {
    return bcJNI.OrbitPattern_toJson(swigCPtr, this);
  }

  public void setAmplitude(long value) {
    bcJNI.OrbitPattern_amplitude_set(swigCPtr, this, value);
  }

  public long getAmplitude() {
    return bcJNI.OrbitPattern_amplitude_get(swigCPtr, this);
  }

  public void setPeriod(long value) {
    bcJNI.OrbitPattern_period_set(swigCPtr, this, value);
  }

  public long getPeriod() {
    return bcJNI.OrbitPattern_period_get(swigCPtr, this);
  }

  public void setCenter(long value) {
    bcJNI.OrbitPattern_center_set(swigCPtr, this, value);
  }

  public long getCenter() {
    return bcJNI.OrbitPattern_center_get(swigCPtr, this);
  }

}
