/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class Player {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Player(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Player obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_Player(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Player(Team team, Planet planet) {
    this(bcJNI.new_Player(team.swigValue(), planet.swigValue()), true);
  }

  public String toString() {
    return bcJNI.Player_toString(swigCPtr, this);
  }

  public Player clone() {
    long cPtr = bcJNI.Player_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Player(cPtr, true);
  }

  public boolean equals(Player other) {
    return bcJNI.Player_equals(swigCPtr, this, Player.getCPtr(other), other);
  }

  public String toJson() {
    return bcJNI.Player_toJson(swigCPtr, this);
  }

  public void setTeam(Team value) {
    bcJNI.Player_team_set(swigCPtr, this, value.swigValue());
  }

  public Team getTeam() {
    return Team.swigToEnum(bcJNI.Player_team_get(swigCPtr, this));
  }

  public void setPlanet(Planet value) {
    bcJNI.Player_planet_set(swigCPtr, this, value.swigValue());
  }

  public Planet getPlanet() {
    return Planet.swigToEnum(bcJNI.Player_planet_get(swigCPtr, this));
  }

}
