/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class ResearchInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ResearchInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResearchInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_ResearchInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ResearchInfo() {
    this(bcJNI.new_ResearchInfo(), true);
  }

  public long getLevel(UnitType branch) {
    return bcJNI.ResearchInfo_getLevel(swigCPtr, this, branch.swigValue());
  }

  public VecUnitType queue() {
    long cPtr = bcJNI.ResearchInfo_queue(swigCPtr, this);
    return (cPtr == 0) ? null : new VecUnitType(cPtr, true);
  }

  public boolean hasNextInQueue() {
    return bcJNI.ResearchInfo_hasNextInQueue(swigCPtr, this);
  }

  public UnitType nextInQueue() {
    return UnitType.swigToEnum(bcJNI.ResearchInfo_nextInQueue(swigCPtr, this));
  }

  public long roundsLeft() {
    return bcJNI.ResearchInfo_roundsLeft(swigCPtr, this);
  }

  public String toJson() {
    return bcJNI.ResearchInfo_toJson(swigCPtr, this);
  }

}
