/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class RocketLandingInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RocketLandingInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RocketLandingInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_RocketLandingInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RocketLandingInfo() {
    this(bcJNI.new_RocketLandingInfo(), true);
  }

  public VecRocketLanding landingsOn(long round) {
    long cPtr = bcJNI.RocketLandingInfo_landingsOn(swigCPtr, this, round);
    return (cPtr == 0) ? null : new VecRocketLanding(cPtr, true);
  }

  public RocketLandingInfo clone() {
    long cPtr = bcJNI.RocketLandingInfo_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new RocketLandingInfo(cPtr, true);
  }

  public String toString() {
    return bcJNI.RocketLandingInfo_toString(swigCPtr, this);
  }

  public String toJson() {
    return bcJNI.RocketLandingInfo_toJson(swigCPtr, this);
  }

  public boolean equals(RocketLandingInfo other) {
    return bcJNI.RocketLandingInfo_equals(swigCPtr, this, RocketLandingInfo.getCPtr(other), other);
  }

}
