/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class RocketLanding {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected RocketLanding(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RocketLanding obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_RocketLanding(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RocketLanding(int rocket_id, MapLocation destination) {
    this(bcJNI.new_RocketLanding(rocket_id, MapLocation.getCPtr(destination), destination), true);
  }

  public RocketLanding clone() {
    long cPtr = bcJNI.RocketLanding_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new RocketLanding(cPtr, true);
  }

  public String toString() {
    return bcJNI.RocketLanding_toString(swigCPtr, this);
  }

  public String toJson() {
    return bcJNI.RocketLanding_toJson(swigCPtr, this);
  }

  public boolean equals(RocketLanding other) {
    return bcJNI.RocketLanding_equals(swigCPtr, this, RocketLanding.getCPtr(other), other);
  }

  public void setRocket_id(int value) {
    bcJNI.RocketLanding_rocket_id_set(swigCPtr, this, value);
  }

  public int getRocket_id() {
    return bcJNI.RocketLanding_rocket_id_get(swigCPtr, this);
  }

  public void setDestination(MapLocation value) {
    bcJNI.RocketLanding_destination_set(swigCPtr, this, MapLocation.getCPtr(value), value);
  }

  public MapLocation getDestination() {
    long cPtr = bcJNI.RocketLanding_destination_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MapLocation(cPtr, false);
  }

}
