/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class StartTurnMessage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StartTurnMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StartTurnMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_StartTurnMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StartTurnMessage() {
    this(bcJNI.new_StartTurnMessage(), true);
  }

  public String toJson() {
    return bcJNI.StartTurnMessage_toJson(swigCPtr, this);
  }

  public void setTime_left_ms(int value) {
    bcJNI.StartTurnMessage_time_left_ms_set(swigCPtr, this, value);
  }

  public int getTime_left_ms() {
    return bcJNI.StartTurnMessage_time_left_ms_get(swigCPtr, this);
  }

  public void setRound(long value) {
    bcJNI.StartTurnMessage_round_set(swigCPtr, this, value);
  }

  public long getRound() {
    return bcJNI.StartTurnMessage_round_get(swigCPtr, this);
  }

}
