/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public enum UnitType {
  Worker(0),
  Knight(1),
  Ranger(2),
  Mage(3),
  Healer(4),
  Factory(5),
  Rocket(6);

  public final int swigValue() {
    return swigValue;
  }

  public static UnitType swigToEnum(int swigValue) {
    UnitType[] swigValues = UnitType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (UnitType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + UnitType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private UnitType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private UnitType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private UnitType(UnitType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

