/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class Unit {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Unit(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Unit obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_Unit(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Unit() {
    this(bcJNI.new_Unit(), true);
  }

  public String toString() {
    return bcJNI.Unit_toString(swigCPtr, this);
  }

  public Unit clone() {
    long cPtr = bcJNI.Unit_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Unit(cPtr, true);
  }

  public String toJson() {
    return bcJNI.Unit_toJson(swigCPtr, this);
  }

  public boolean equals(Unit other) {
    return bcJNI.Unit_equals(swigCPtr, this, Unit.getCPtr(other), other);
  }

  public int id() {
    return bcJNI.Unit_id(swigCPtr, this);
  }

  public Team team() {
    return Team.swigToEnum(bcJNI.Unit_team(swigCPtr, this));
  }

  public long researchLevel() {
    return bcJNI.Unit_researchLevel(swigCPtr, this);
  }

  public UnitType unitType() {
    return UnitType.swigToEnum(bcJNI.Unit_unitType(swigCPtr, this));
  }

  public Location location() {
    long cPtr = bcJNI.Unit_location(swigCPtr, this);
    return (cPtr == 0) ? null : new Location(cPtr, true);
  }

  public long health() {
    return bcJNI.Unit_health(swigCPtr, this);
  }

  public long maxHealth() {
    return bcJNI.Unit_maxHealth(swigCPtr, this);
  }

  public long visionRange() {
    return bcJNI.Unit_visionRange(swigCPtr, this);
  }

  public int damage() {
    return bcJNI.Unit_damage(swigCPtr, this);
  }

  public long attackRange() {
    return bcJNI.Unit_attackRange(swigCPtr, this);
  }

  public long movementHeat() {
    return bcJNI.Unit_movementHeat(swigCPtr, this);
  }

  public long attackHeat() {
    return bcJNI.Unit_attackHeat(swigCPtr, this);
  }

  public long movementCooldown() {
    return bcJNI.Unit_movementCooldown(swigCPtr, this);
  }

  public long attackCooldown() {
    return bcJNI.Unit_attackCooldown(swigCPtr, this);
  }

  public short isAbilityUnlocked() {
    return bcJNI.Unit_isAbilityUnlocked(swigCPtr, this);
  }

  public long abilityHeat() {
    return bcJNI.Unit_abilityHeat(swigCPtr, this);
  }

  public long abilityCooldown() {
    return bcJNI.Unit_abilityCooldown(swigCPtr, this);
  }

  public long abilityRange() {
    return bcJNI.Unit_abilityRange(swigCPtr, this);
  }

  public short workerHasActed() {
    return bcJNI.Unit_workerHasActed(swigCPtr, this);
  }

  public long workerBuildHealth() {
    return bcJNI.Unit_workerBuildHealth(swigCPtr, this);
  }

  public long workerRepairHealth() {
    return bcJNI.Unit_workerRepairHealth(swigCPtr, this);
  }

  public long workerHarvestAmount() {
    return bcJNI.Unit_workerHarvestAmount(swigCPtr, this);
  }

  public long knightDefense() {
    return bcJNI.Unit_knightDefense(swigCPtr, this);
  }

  public long rangerCannotAttackRange() {
    return bcJNI.Unit_rangerCannotAttackRange(swigCPtr, this);
  }

  public long rangerMaxCountdown() {
    return bcJNI.Unit_rangerMaxCountdown(swigCPtr, this);
  }

  public short rangerIsSniping() {
    return bcJNI.Unit_rangerIsSniping(swigCPtr, this);
  }

  public MapLocation rangerTargetLocation() {
    long cPtr = bcJNI.Unit_rangerTargetLocation(swigCPtr, this);
    return (cPtr == 0) ? null : new MapLocation(cPtr, true);
  }

  public long rangerCountdown() {
    return bcJNI.Unit_rangerCountdown(swigCPtr, this);
  }

  public long healerSelfHealAmount() {
    return bcJNI.Unit_healerSelfHealAmount(swigCPtr, this);
  }

  public short structureIsBuilt() {
    return bcJNI.Unit_structureIsBuilt(swigCPtr, this);
  }

  public long structureMaxCapacity() {
    return bcJNI.Unit_structureMaxCapacity(swigCPtr, this);
  }

  public VecUnitID structureGarrison() {
    long cPtr = bcJNI.Unit_structureGarrison(swigCPtr, this);
    return (cPtr == 0) ? null : new VecUnitID(cPtr, true);
  }

  public short isFactoryProducing() {
    return bcJNI.Unit_isFactoryProducing(swigCPtr, this);
  }

  public UnitType factoryUnitType() {
    return UnitType.swigToEnum(bcJNI.Unit_factoryUnitType(swigCPtr, this));
  }

  public long factoryRoundsLeft() {
    return bcJNI.Unit_factoryRoundsLeft(swigCPtr, this);
  }

  public long factoryMaxRoundsLeft() {
    return bcJNI.Unit_factoryMaxRoundsLeft(swigCPtr, this);
  }

  public short rocketIsUsed() {
    return bcJNI.Unit_rocketIsUsed(swigCPtr, this);
  }

  public int rocketBlastDamage() {
    return bcJNI.Unit_rocketBlastDamage(swigCPtr, this);
  }

  public long rocketTravelTimeDecrease() {
    return bcJNI.Unit_rocketTravelTimeDecrease(swigCPtr, this);
  }

}
