/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package bc;

public class Veci32 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Veci32(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Veci32 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bcJNI.delete_Veci32(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Veci32() {
    this(bcJNI.new_Veci32(), true);
  }

  public String toString() {
    return bcJNI.Veci32_toString(swigCPtr, this);
  }

  public Veci32 clone() {
    long cPtr = bcJNI.Veci32_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Veci32(cPtr, true);
  }

  public long size() {
    return bcJNI.Veci32_size(swigCPtr, this);
  }

  public int get(long index) {
    return bcJNI.Veci32_get(swigCPtr, this, index);
  }

}
